local bash = require("bash")
local tmux = require("utils.tmux")
local json = require("cjson")
local dir = tmux.getShipDir()
local cargo = tmux.getCargo()
dir = Dir_to_filename(dir)
bash.exec("mkdir -p " .. Dockyard .. "/" .. dir)
local cargoJson = json.encode(cargo)
bash.write(cargoJson, Dockyard .. "/" .. dir .. "/cargo")
