local strings = require("strings")
local bash = require("bash")
local tmux = require("utils.tmux")
local json = require("cjson")

return function(...)
	local cargo = tmux.getCargo()
	local name = GetCargoPath()
	bash.exec("mkdir -p " .. name)
	local cargoJson = json.encode(cargo)
	print(cargoJson)
	bash.write(name .. "/cargo", cargoJson)
	local fleet = tmux.execRet('ls -F "#{session_last_attached}|#{session_path}" | sort -n | cut -d"|" -f2')
	fleet = strings.split(fleet, "\n")
	fleet = json.encode(fleet)
	bash.write(Fleet, fleet)
	print(fleet)
end
