echo "tmux bashrc"

alias test1="ls -l"
test2() {
	echo testing
}

nvim() {
	plugin="$(dirname "$HARBONIZER_DIR")"
	command nvim --cmd "lua package.path = '$plugin/?.lua;' .. package.path; require('harbonizer.nvim.test')" "$@"
}
