echo "tmux bashrc"

alias test1="ls -l"
test2() {
	echo testing
}

nvim() {
	plugin="$(dirname "$HARBONIZER_DIR")"
	command nvim -c "lua dofile('/home/viktor/dev/lua/harbonizer/nvim/plugins/test.lua')" "$@"
}
